version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Akka.Bootstrap.PCF
    versions:
    - 0.5.0
    - 0.5.1
  - dependency-name: Akka.TestKit.Xunit2
    versions:
    - 1.4.16
    - 1.4.17
    - 1.4.18
  - dependency-name: Microsoft.IO.RecyclableMemoryStream
    versions:
    - 1.4.0
    - 1.4.1
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.8.3
    - 16.9.1
  - dependency-name: Petabridge.Cmd.Host
    versions:
    - 0.8.2
